### ISSUE TITLE
How many items per slide in carousel

### ISSUE THREAD

**Issue by Radcliffe** [backdrop-contrib/views_bootstrap#18]
See https://www.drupal.org/project/views_bootstrap/issues/2445671 for details.

**Comment by stpaultim** [comment]
I tried to review this option today, but I am unable to get a carousel to working in the currently released version of views_bootstrap.

**Comment by stpaultim** [comment]
I think you need to update this pull request based upon changes to the code base for me to test it. I would usually test it by pulling down the code from this branch. But, this branch is broken.

**Comment by Radcliffe** [comment]
The branch was broken because some template files were in the wrong location, but this does not affect the patch. I was able to apply it successfully.
