### ISSUE TITLE
Device size support in Bootstrap Thumbnails and Grid column classes

### ISSUE THREAD

**Issue by Radcliffe** [backdrop-contrib/views_bootstrap#20]
See https://www.drupal.org/project/views_bootstrap/issues/2203111 for details.

**Comment by bugfolder** [comment]
This will be addressed by PR https://github.com/backdrop-contrib/views_bootstrap/pull/55.

**Comment by bugfolder** [comment]
Housekeeping: PR https://github.com/backdrop-contrib/views_bootstrap/pull/55 was merged, so closing this.
