### ISSUE TITLE
Views Bootstrap breaks format of permissions page

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/views_bootstrap#23]
This may be related to this issue: https://github.com/backdrop-contrib/views_bootstrap/issues/7

![permissions___localhost](https://user-images.githubusercontent.com/3144571/48985999-5388b000-f0d4-11e8-871b-7c45b8d694bc.png)

![permissions___localhost](https://user-images.githubusercontent.com/3144571/48986012-8d59b680-f0d4-11e8-9e04-506b63e8dba0.png)

**Comment by stpaultim** [comment]
Thanks @Radcliffe for pointing out that I can block the modules from loading Bootstrap on specific pages in the configuration. 

Go to: admin/config/user-interface/views_bootstrap
Add this to list: admin/config/people/permissions

Maybe it would make sense to add certain pages to this list by default if we know that they cause problems and then allow users to override them later if they have specific cause.

**Comment by Radcliffe** [comment]
Fixed by #29.
