### ISSUE TITLE
Block views bootstrap on admin pages?

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/views_bootstrap#24]
We have found a couple of cases where Views Bootstrap is in conflict with the admin theme. https://github.com/backdrop-contrib/views_bootstrap/issues/7
https://github.com/backdrop-contrib/views_bootstrap/issues/23

Users can specify which pages they want views bootstrap to effect on the settings page, but we should make it easier and/or provide some good default behavior. Options:

1. We could have a single checkbox that says "Allow views bootstrap on admin pages"
2. We could block pages that we know are problems by default on in the config page but allow users to change the settings
3. We could just block the module on all admin pages no matter what. 
4. We could leave module as it is, but provide better documentation for users to understand the problem and adjust settings.

**Comment by Radcliffe** [comment]
Superseded by #29.
