### ISSUE TITLE
Bootstrap not working in views preview (dev version)

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/views_bootstrap#31]
The current DEV branch of the module does not work in preview mode inside of views. 

If I check out Version 1.x-1.1.0 and preview an accordion view, I can see the accordion in preview mode (see 1st image) after I update to the newest version of the module (the dev version) the accordion no longer works in preview mode (see 2nd image). 

I tried this with the "Include Bootstrap CSS & JS when used by Views" box checked. I also tried unchecking this box and enabling the "Bootstrap Lite" theme. With the "Boostrap Lite" theme, the accordion worked on the actual view page, but DID NOT work in the preview.

![test__content____backdrop](https://user-images.githubusercontent.com/3144571/50730788-1542cf80-111b-11e9-930e-33396832e29d.png)

![test__content____backdrop](https://user-images.githubusercontent.com/3144571/50730816-014b9d80-111c-11e9-815e-f92f8c723400.png)

Pull Request: https://github.com/backdrop-contrib/views_bootstrap/pull/34

**Comment by stpaultim** [comment]
Is this pull request the cause?
https://github.com/backdrop-contrib/views_bootstrap/issues/24 or this one https://github.com/backdrop-contrib/views_bootstrap/issues/28

**Comment by Radcliffe** [comment]
PR #29 prevents Bootstrap from being loaded on any admin page, including views previews.

**Comment by stpaultim** [comment]
Both of my guesses were wrong. :-(

I think it's pretty helpful to be able to see that the accordion is working in views preview. I can imagine arguments about why it's not necessary. But, I would hate to loose this ability unless there is good reason. 

Can we address the other issues while still be able to preview the bootstrap effect? I'm interested in what others think.

**Comment by Radcliffe** [comment]
I think that we should restore the settings for specifying the pages that load Bootstrap.

**Comment by stpaultim** [comment]
I tested the pull request and if fixes the most important issues. As indicated by my comments below, I'm still a little worried that developers might forget about the need to check the "Include Bootstrap CSS & JS when used by Views" box. Especially, because bootstrap seems to be working in the views preview (after this patch). This sense that the module is working might cause a developer to assume that the module is configured correctly and that something else is wrong. 

1) Have we updated the READ ME file to alert the user/developer to check the configuration?
2) Can we create a status or information alert message upon installation, reminding the developer to check the configuration?

Having said all of this, I would be comfortable committing this PR and releasing a new version of module. I think we need to get all the improvements we've made released. We can make this better later.

> This is great and seems to address the problem I identified.

> I hate to nitpick, but the PR makes sure that bootstrap is loaded on the preview page, even when "Include Bootstrap CSS & JS when used by Views" IS NOT checked and the user is NOT using a Bootstrap theme.

> This means that bootstrap is working in the views preview, even when it is not working for regular users. This is only a problem, if the developer has not configured the module properly. But, I'm afraid that could be confusing to developers.

> Is there a way to notify/remind users of the importance of checking the "Include Bootstrap CSS & JS when used by Views" box if their view is not working?

**Comment by stpaultim** [comment]
I added some text to ReadMe file to emphasize the configuration option. I am not sure if that is enough.
