### ISSUE TITLE
Discussion about change to settings

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/views_bootstrap#33]
Just noticed that in the last version of the module, the user had the ability to load bootstrap on all pages or ONLY on specific pages, user could list whichever pages they wanted.

With this pull request (https://github.com/backdrop-contrib/views_bootstrap/issues/28), we changed that to only allow the user to check or not to check "Include Bootstrap CSS & JS when used by Views."

Is there any loss in functionality there?
Is is a problem?

NOTE: I am not clear if this is a problem. I just created this issue to see if anyone else thinks it might be a problem. I think the change is probably fine, unless it is what is responsible for causing the module to NOT work in views preview.

**Comment by Radcliffe** [comment]
I think that there is a problem.

Several issues were reported regarding conflicts between Bootstrap and the admin theme. These issues were resolved in PR #29 by preventing the loading of Bootstrap assets on admin pages. But although most admin pages do not need need Bootstrap, we do want it loaded when previewing a Views Bootstap view.

**Comment by daggerhart** [comment]
Submitted a PR that forces assets to be loaded when previewing a view that uses a views_bootstrap style plugin. This approach is very much automatic and can't be disabled. If you would prefer an approach that is configurable as another module setting, that would be fairly easy to do.

Thoughts & feedback welcome as always.
