### ISSUE TITLE
Remind user to include Bootstrap assets after installation

### ISSUE THREAD

**Issue by Radcliffe** [backdrop-contrib/views_bootstrap#44]
When the module is installed, it might be helpful to remind the user that they must select the option to include Bootstrap assets if they are not using a Bootstrap based theme.

**Comment by stpaultim** [comment]
This seems to have been fixed already. 

![image](https://github.com/user-attachments/assets/094b8937-abf8-4d7a-9dcc-37a4b389cb99)
