### ISSUE TITLE
Stepping down as co-maintainer

### ISSUE THREAD

**Issue by Radcliffe** [backdrop-contrib/views_bootstrap#58]
I wish to step down as a co-maintainer of this project, since I don't feel that I will be able to respond to issues in a timely manner.

**Comment by stpaultim** [comment]
@Radcliffe - Thanks for your help with the project David. I'll remove you as co-maintainer ASAP. Hopefully this weekend.

**Comment by stpaultim** [comment]
@Radcliffe - Thanks so much for your past help with this module. I've removed you as co-maintainer from the Readme file.
