### ISSUE TITLE
Bootstrap theme conflicts with Backdrop admin theme

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/views_bootstrap#7]
When I turn on the Views Bootstrap module the css for bootstrap overrides the color of the labels in the views control panel and makes them white (invisible). This overrides the color designated by the Seven theme. Not sure if this is best corrected in the Views Bootstrap module or in the Seven theme? 

Shouldn't the Seven theme automatically override other css on "admin/...." pages?

![devtools_-_rivertonb_triplo_admin_structure_views_view_faq](https://user-images.githubusercontent.com/3144571/43361911-2711b786-92a3-11e8-81b1-1df148761940.png)

![faq__content____riverton](https://user-images.githubusercontent.com/3144571/43361890-c682c5d6-92a2-11e8-8e13-2b8e502ca4e1.png)

**Comment by Radcliffe** [comment]
This is related to #4 .
